INSERT INTO users (user_handle, email_address, first_name, last_name, phonenumber) 
VALUES 
('pesstunky47', 'pesstunky@gmail.com', 'Jesús', 'Reyes', '111111111'),
('andromeda603', 'andromeda603@gmail.com', 'Andrés', 'García', '111111112'),
('leonardodicaprio74', 'leo_dicaprio@gmail.com', 'Leonardo', 'DiCaprio', '111111113'),
('angelinajolie72', 'angelina_jolie@gmail.com', 'Angelina', 'Jolie', '111111114'),
('bradpitt63', 'brad_pitt@gmail.com', 'Brad', 'Pitt', '111111115'),
('tomhanks56', 'tom_hanks@gmail.com', 'Tom', 'Hanks', '111111116'),
('merylstreep49', 'meryl_streep@gmail.com', 'Meryl', 'Streep', '111111117'),
('willsmith68', 'will_smith@gmail.com', 'Will', 'Smith', '111111118'),
('jenniferaniston53', 'jennifer_aniston@gmail.com', 'Jennifer', 'Aniston', '111111119'),
('georgeclooney61', 'george_clooney@gmail.com', 'George', 'Clooney', '111111120'),
('angelamerkel64', 'angela_merkel@gmail.com', 'Angela', 'Merkel', '111111121'),
('barackobama60', 'barack_obama@gmail.com', 'Barack', 'Obama', '111111122'),
('elizabethii95', 'elizabeth_ii@gmail.com', 'Elizabeth', 'II', '111111123'),
('leonelmessi34', 'lionel_messi@gmail.com', 'Lionel', 'Messi', '111111124'),
('serenawilliams40', 'serena_williams@gmail.com', 'Serena', 'Williams', '111111125'),
('taylorswift33', 'taylor_swift@gmail.com', 'Taylor', 'Swift', '111111126'),
('arianagrande28', 'ariana_grande@gmail.com', 'Ariana', 'Grande', '111111127'),
('dwaynejohnson49', 'dwayne_johnson@gmail.com', 'Dwayne', 'Johnson', '111111128'),
('kyliejenner24', 'kylie_jenner@gmail.com', 'Kylie', 'Jenner', '111111129'),
('cristianoronaldo37', 'cristiano_ronaldo@gmail.com', 'Cristiano', 'Ronaldo', '111111130'),
('oprahwinfrey68', 'oprah_winfrey@gmail.com', 'Oprah', 'Winfrey', '111111131'),
('elrubiusOMG', 'ruben_doblas@gmail.com', 'Rubén', 'Doblas', '111111132'),
('auronplay', 'raúl_álvarez@gmail.com', 'Raúl', 'Álvarez', '111111133'),
('lolitofdez35', 'manuel_fernández@gmail.com', 'Manuel', 'Fernández', '111111134'),
('anaguerra30', 'ana_guerra@gmail.com', 'Ana', 'Guerra', '111111135'),
('donpatricio29', 'patricio_martínez@gmail.com', 'Patricio', 'Martínez', '111111136'),
('ayax23', 'manuel_gonzález@gmail.com', 'Manuel', 'González', '111111137'),
('chikilicuatre40', 'rodolfo_chikilicuatre@gmail.com', 'Rodolfo', 'Chikilicuatre', '111111138'),
('davidbisbal42', 'david_bisbal@gmail.com', 'David', 'Bisbal', '111111139'),
('rosaliavt44', 'rosalía_verdú@gmail.com', 'Rosalía', 'Verdú', '111111140'),
('pabloalboran39', 'pablo_alborán@gmail.com', 'Pablo', 'Alborán', '111111141'),
('alexelcapo28', 'alejandro_muñoz@gmail.com', 'Alejandro', 'Muñoz', '111111142'),
('zorman33', 'manu_zorman@gmail.com', 'Manuel', 'Zorman', '111111143'),
('leiva41', 'jose_miguel_conejo@gmail.com', 'José Miguel', 'Conejo', '111111144'),
('srtacaro45', 'laura_lozano@gmail.com', 'Laura', 'Lozano', '111111145'),
('wismichu30', 'ismael_prego@gmail.com', 'Ismael', 'Prego', '111111146'),
('lolaindigomusic34', 'maría_rodríguez@gmail.com', 'María', 'Rodríguez', '111111147'),
('skone38', 'carlos_ortiz@gmail.com', 'Carlos', 'Ortiz', '111111148'),
('juanes48', 'juan_espinosa@gmail.com', 'Juan', 'Espinosa', '111111149'),
('willyrex', 'willyrex@gmail.com', 'Guillermo', 'Díaz', '111111150'),
('vegetta777', 'vegetta777@gmail.com', 'Samuel', 'De Luque', '111111151'),
('sofiaellar47', 'sofía_morales@gmail.com', 'Sofía', 'Morales', '111111152'),
('cepeda45', 'luis_céspedes@gmail.com', 'Luis', 'Céspedes', '111111153'),
('lolaindi41', 'lolita_indigo@gmail.com', 'Lolita', 'Indigo', '111111154'),
('dross32', 'ángel_david_revilla@gmail.com', 'Ángel David', 'Revilla', '111111155'),
('luisitorey48', 'luis_torres@gmail.com', 'Luis', 'Torres', '111111156'),
('nilojeda', 'nilojeda@gmail.com', 'Nil', 'Ojeda', '111111157'),
('wendolinga34', 'wendy_lozano@gmail.com', 'Wendy', 'Lozano', '111111158'),
('valentinrodriguez42', 'valentín_rodríguez@gmail.com', 'Valentín', 'Rodríguez', '111111159'),
('elarrebato14', 'franciscojavierlobadon@gmail.com', 'Francisco', 'Lobadón', '111111160'),
('ibaillanos', 'ibai@gmail.com', 'Ibai', 'Llanos', '111111161'),
('illojuan', 'illojuan@gmail.com', 'Illo', 'Juan', '111111162'),
('xokas', 'xokas@gmail.com', 'Joaquín', 'Dominguez', '111111163'),
('knkro', 'knkro@gmail.com', 'Sergio', 'García', '111111164');

delete from users where user_id between 973 and 1026;

select * from users;

-- añade más a tu gusto, en mi caso no podía faltar mi nombre y el arrebato además he metido también a Aronplay, willy, vegetta777 y una pila de youtubers JIJIJIJA

insert into followers (following_id, follower_id) values 
(1, 2), 
(1, 3), 
(1, 4), 
(1, 5), 
(1, 6), 
(1, 7), 
(1, 8), 
(1, 9), 
(1, 10), 
(1, 11), 
(2, 1), 
(2, 3), 
(2, 4), 
(2, 5), 
(2, 6), 
(3, 1), 
(3, 2), 
(3, 4), 
(3, 5), 
(3, 6), 
(4, 1), 
(4, 2), 
(4, 3), 
(4, 5), 
(4, 6), 
(5, 1), 
(5, 2), 
(5, 3), 
(5, 4), 
(5, 6), 
(6, 1), 
(6, 2), 
(7, 9), 
(7, 10), 
(7, 11), 
(7, 12), 
(8, 7), 
(8, 9), 
(8, 10), 
(8, 11), 
(8, 12), 
(9, 7), 
(9, 8), 
(9, 10), 
(9, 11), 
(9, 12), 
(10, 7), 
(10, 8), 
(10, 9), 
(10, 11), 
(10, 12), 
(11, 7), 
(11, 8), 
(11, 9), 
(11, 10), 
(11, 12), 
(12, 7), 
(12, 8), 
(12, 9), 
(12, 10), 
(12, 11), 
(13, 14), 
(13, 15), 
(13, 16), 
(13, 17), 
(13, 18), 
(14, 13), 
(14, 15), 
(14, 16), 
(14, 17), 
(14, 18), 
(15, 13), 
(15, 14), 
(15, 16), 
(15, 17), 
(15, 18), 
(16, 13), 
(16, 14), 
(16, 15), 
(16, 17), 
(16, 18), 
(17, 13), 
(17, 14), 
(17, 15), 
(17, 16), 
(17, 18), 
(18, 13), 
(18, 14), 
(18, 15), 
(18, 16), 
(18, 17), 
(19, 20), 
(19, 21), 
(19, 22), 
(19, 23), 
(19, 24), 
(20, 19), 
(20, 21), 
(20, 22), 
(20, 23), 
(20, 24), 
(21, 19), 
(21, 20), 
(21, 22), 
(21, 23), 
(21, 24), 
(22, 19), 
(22, 20), 
(22, 21), 
(22, 23), 
(22, 24), 
(23, 19), 
(23, 20), 
(23, 21), 
(23, 22), 
(23, 24), 
(24, 19), 
(24, 20), 
(24, 21), 
(24, 22), 
(24, 23), 
(25, 26), 
(25, 27), 
(25, 28), 
(25, 29), 
(25, 30), 
(26, 25), 
(26, 27), 
(26, 28), 
(26, 29), 
(26, 30), 
(27, 25), 
(27, 26), 
(27, 28), 
(27, 29), 
(27, 30), 
(28, 25), 
(28, 26), 
(28, 27), 
(28, 29), 
(28, 30), 
(29, 25), 
(29, 26), 
(29, 27), 
(29, 28), 
(29, 30), 
(30, 25), 
(30, 26), 
(30, 27), 
(30, 28), 
(30, 29), 
(31, 32), 
(31, 33), 
(31, 34), 
(31, 35), 
(31, 36), 
(32, 31), 
(32, 33), 
(32, 34), 
(32, 35), 
(32, 36), 
(33, 31), 
(33, 32), 
(33, 34), 
(33, 35), 
(33, 36), 
(34, 31), 
(34, 32), 
(34, 33), 
(34, 35), 
(34, 36), 
(35, 31), 
(35, 32), 
(35, 33), 
(35, 34), 
(35, 36), 
(36, 31), 
(36, 32), 
(36, 33), 
(36, 34), 
(36, 35), 
(37, 38), 
(37, 39), 
(37, 40), 
(37, 41), 
(37, 42), 
(38, 37), 
(38, 39), 
(38, 40), 
(38, 41), 
(38, 42), 
(39, 37), 
(39, 38), 
(39, 40), 
(39, 41), 
(39, 42), 
(40, 37), 
(40, 38), 
(40, 39), 
(40, 41), 
(40, 42), 
(41, 37), 
(41, 38), 
(41, 39), 
(41, 40), 
(41, 42), 
(42, 37), 
(42, 38), 
(42, 39), 
(42, 40), 
(42, 41), 
(43, 44), 
(43, 45), 
(43, 46), 
(43, 47), 
(43, 48), 
(44, 43), 
(44, 45), 
(44, 46), 
(44, 47), 
(44, 48), 
(45, 43), 
(45, 44), 
(45, 46), 
(45, 47), 
(45, 48), 
(46, 43), 
(46, 44), 
(46, 45), 
(46, 47), 
(46, 48), 
(47, 43), 
(47, 44), 
(47, 45), 
(47, 46), 
(47, 48), 
(48, 43), 
(48, 44), 
(48, 45), 
(48, 46), 
(48, 47), 
(49, 50), 
(49, 51), 
(49, 52), 
(49, 53), 
(49, 54), 
(50, 49), 
(50, 51), 
(50, 52), 
(50, 53), 
(50, 54), 
(51, 49), 
(51, 50), 
(51, 52), 
(51, 53), 
(51, 54), 
(52, 49), 
(52, 50), 
(52, 51), 
(52, 53), 
(52, 54), 
(53, 49), 
(53, 50), 
(53, 51), 
(53, 52), 
(53, 54), 
(54, 49), 
(54, 50), 
(54, 51), 
(54, 52), 
(54, 53);

INSERT INTO tweets (tweet_text, user_id) 
VALUES 
("La vida es como un café: amarga, pero te mantiene despierto. ☕️😅", 1),
("¡No puedo creer que haya personas que prefieran el té sobre el café! ¿Acaso disfrutan de la vida sin emoción? ☕️😒", 1),
("Acabo de darme cuenta de que mi despertador es mi peor enemigo y mi mejor amigo al mismo tiempo. ⏰🤔", 1),

("Siempre me sorprende cómo una simple conversación con un desconocido puede alegrar mi día. La gente es sorprendente. 💬🙂", 2),
("¿Alguien más se siente incómodo cuando la persona de al lado del tren está leyendo tu pantalla por encima de tu hombro? 😳📱", 2),
("¡No puedo evitar sonreír cuando alguien me regala un 'buenos días' en la calle! Pequeños gestos que hacen el día más brillante. ☀️😊", 2),

("A veces, me pregunto si los pájaros se ríen de nosotros cuando corremos bajo la lluvia tratando de evitar mojarnos. 🐦☔️", 3),
("¿Alguien más se ha dado cuenta de que siempre necesitas un café extra los viernes? Es como si el fin de semana estuviera pidiendo energía adicional. ☕️💪", 3),
("Acabo de recordar que mañana es lunes. Creo que mi fin de semana acaba de perder un poco de su brillo. 😅🌟", 3),

("¿Alguna vez has sentido que tu mascota te juzga cuando decides quedarte en casa viendo Netflix en lugar de salir a caminar? 🐶📺", 4),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 4),
("Siempre que intento hacer algo productivo, mi gato decide que es el momento perfecto para dormir en mi regazo. ¿Coincidencia? No lo creo. 🐱💤", 4),

("¿Alguien más se emociona al encontrar dinero extra en los bolsillos de su ropa? Es como un pequeño regalo de tu yo pasado. 💸🎁", 5),
("Acabo de descubrir que mi nevera es como un agujero negro: cualquier alimento que entre en ella parece desaparecer misteriosamente. 🍽️🌌", 5),
("¿Alguna vez has tenido un día tan malo que sientes que necesitas un manual de instrucciones solo para sobrevivir? 😅📖", 5),

("Creo que mi superpoder es siempre llegar tarde a las tendencias. Justo cuando todos están hablando de algo, yo recién empiezo a interesarme. 🦸‍♂️💤", 6),
("¿Alguien más encuentra irónico que la palabra 'abreviatura' sea tan larga? 🤔✂️", 6),
("Acabo de realizar que soy la persona que se ríe más alto en el cine. Espero no haber arruinado ninguna escena dramática. 😅🎬", 6),

("¿Alguna vez has deseado poder poner tu cerebro en modo avión? Sería genial poder desconectar por un rato. ✈️🧠", 7),
("He descubierto que mi capacidad para recordar nombres está directamente relacionada con cuánto me importa la persona. 😅📝", 7),
("¿Alguien más piensa que la pizza es como la solución a todos los problemas? Pizza: la respuesta universal. 🍕🌎", 7),

("Siempre que trato de levantar peso en el gimnasio, siento que estoy participando en una competencia contra las máquinas. Y ellas siempre ganan. 🏋️‍♂️💪", 8),
("¿Alguna vez te has sentido como un detective tratando de encontrar tus llaves perdidas en tu propia casa? Es una misión imposible. 🔍🔑", 8),
("Creo que mi mayor talento es hacer preguntas incómodas en los momentos más inoportunos. Soy un experto en generar silencios incómodos. 🤫❓", 8),

("Acabo de darme cuenta de que el único momento en que soy un excelente cantante es cuando estoy solo en la ducha. El resto del tiempo, soy un desastre. 🚿🎤", 9),
("¿Alguien más tiene la habilidad de imaginar las peores situaciones posibles en su cabeza y luego preocuparse por ellas? Es como un superpoder de ansiedad. 🦸‍♂️😬", 9),
("Estoy convencido de que las escaleras mecánicas tienen la capacidad de hacer que la gente olvide cómo caminar. Siempre hay alguien parado bloqueando el camino. 🤦‍♂️🛑", 9),

("Cada vez que intento tomar una siesta rápida, mi mente decide recordarme todas las cosas que tengo pendientes. Es como un recordatorio en bucle. 😴🔄", 10),
("¿Alguien más siente que las plantas tienen una vida más emocionante que la suya? Solo están ahí, recibiendo luz solar y creciendo. 🌱☀️", 10),
("Acabo de descubrir que mi nevera es un tesoro de comida olvidada. Siempre encuentro algo nuevo cada vez que la limpio. 🍗🥦", 10),

("Creo que mi súper poder es siempre atraer al mosquito más persistente en cualquier habitación. Si hay uno, vendrá a por mí. 🦟🎯", 11),
("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 11),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 11),

("Acabo de realizar que mi gato tiene una habilidad especial para sentarse en cualquier objeto que deje sobre la mesa. Siempre encuentra la manera de ser el centro de atención. 🐱🤷‍♂️", 12),
("¿Alguien más encuentra irónico que las dietas comiencen los lunes? ¿Acaso el universo está burlándose de nosotros? 🤔🥗", 12),
("Estoy convencido de que mi gato tiene una vida secreta cuando no estoy en casa. Probablemente sea un agente secreto felino. 🐱🕵️‍♂️", 12),

("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 13),
("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 13),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 13),

("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 14),
("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 14),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 14),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 15),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 15),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 15),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 16),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 16),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 16),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 17),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 17),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 17),

('VIVA ESPAÑA, VIVA EL REY, VIVA EL ORDEN Y LA LEY',2),
('Tener un perro racista es una de las mejores cosas que me ha pasado en la vida',2),
('Esto con Franco no pasaba',2),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 18),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 18),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 18),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 19),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 19),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 19),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 20),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 20),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 20),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 21),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 21),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 21),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 22),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 22),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 22),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 23),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 23),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 23),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 24),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 24),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 24),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 25),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 25),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 25),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 26),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 26),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 26),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 27),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 27),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 27),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 28),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 28),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 28),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 29),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 29),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 29),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 30),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 30),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 30),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 31),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 31),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 31),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 32),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 32),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 32),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 33),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 33),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 33),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 34),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 34),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 34),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 35),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 35),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 35),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 36),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 36),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 36),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 37),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 37),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 37),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 38),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 38),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 38),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 39),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 39),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 39),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 40),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 40),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 40),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 41),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 41),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 41),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 42),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 42),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 42),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 43),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 43),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 43),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 44),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 44),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 44),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 45),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 45),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 45),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 46),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 46),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 46),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 47),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 47),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 47),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 48),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 48),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 48),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 49),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 49),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 49),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 50),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 50),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 50),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 51),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 51),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 51),

("¿Alguien más tiene la extraña habilidad de hacer que se caiga cualquier cosa que tenga en la mano? Es como un superpoder anti-gravedad. 🤷‍♂️🔍", 52),
("Acabo de darme cuenta de que siempre termino comprando más cosas de las que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 52),
("Siempre me sorprende cómo una simple sonrisa puede cambiar completamente mi día. La felicidad es contagiosa. 😊🌟", 52),

("¿Alguna vez te has dado cuenta de que siempre te sientes más cansado los lunes? Es como si el fin de semana nunca hubiera pasado. 😴📆", 53),
("Creo que mi gato tiene una habilidad especial para aparecer justo cuando estoy a punto de sentarme. Siempre está en el lugar equivocado en el momento equivocado. 🐱💺", 53),
("He descubierto que siempre termino comprando más de lo que necesito cuando voy al supermercado con hambre. Es un error recurrente. 🛒🍕", 53),

("¿Alguien más se siente como un malabarista tratando de equilibrar trabajo, vida social y autocuidado? Es un acto de malabarismo constante. 🤹‍♂️💼", 54),
("No entiendo por qué el botón de snooze del despertador está tan cerca del de apagar. Es como si estuviera pidiendo que lo ignoremos. ⏰❌", 54),
("Cada vez que veo una película de terror, me pregunto por qué los personajes siempre deciden dividirse para explorar lugares oscuros. ¡Claramente nunca han visto una película de terror antes! 🎬😱", 54);
